name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  integration-test:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres
          # Provide the password for postgres
          env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: test
          # Set health checks to wait until postgres has started
          ports:
          # Maps tcp port 5432 on service container to the host
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup

      - name: Migrate Database
        run: pnpm db:push
        # env:
        #   DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Running Integration Tests...
        run: pnpm int:test
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Integration Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "unit-test",
            "state": "success",
            "description": "Integration Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Integration Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "unit-test",
            "state": "failure",
            "description": "Integration Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
